final currency_list = {
  "1ST": "FirstBlood",
  "2GIVE": "GiveCoin",
  "808": "808Coin",
  "AGI": "SingularityNET",
  "AGRS": "IDNI-Agoras",
  "AI": "POLY-AI",
  "AID": "AidCoin",
  "ATS": "Authorship",
  "AUR": "Auroracoin",
  "AVAX": "Avalanche",
  "AVT": "Aventus",
  "BTC": "Bitcoin",
  "BTCB": "Bitcoin BEP2",
  "BTCD": "BitcoinDark",
  "BTCP": "Bitcoin-Private",
  "BTT": "BitTorrent",
  "BTX": "Bitcore",
  "DOGE": "DogeCoin",
  "DOPE": "DopeCoin",
  "ETC": "Ethereum-Classic",
  "ETH": "Ethereum",
  "ETHD": "Ethereum-Dark",
  "ETHOS": "Ethos",
  "FCT": "Factom",
  "FIL": "Filecoin",
  "GAM": "Gambit",
  "GAME": "GameCredits",
  "SYNX": "Syndicate",
  "SYS": "SysCoin",
};
